version: "3"

services:
  web:
    build: .
    container_name: slim-web
    ports:
      - 8080:8080
    working_dir: /home/${USER}/project
    volumes:
      - .:/home/${USER}/project
    command: sh ./docker/web/run.sh
